(function(){'use strict';
const SKILLS=[['feet_to_floor','Standing and falling safely'],['pin_escapes','Getting out from bottom'],['guard','Using the legs from bottom'],['guard_retention','Keeping the legs in front'],['submission_escapes','Getting safe from a hold'],['pinning','Staying on top'],['base_retention','Keeping balance on top'],['guard_passing','Getting past the legs'],['submissions','Finishing a hold safely']];
const CONTEXTS=['Game','Positional','Live','Practice','Other'];const $=id=>document.getElementById(id);const f={student:$('student'),week:$('week-of'),skill:$('main-skill'),problem:$('problem'),observed:$('observed-action'),next:$('next-action'),easier:$('getting-easier')};let pdfPrintInvoked=false;
function monday(){const d=new Date(),day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d.toISOString().slice(0,10)}
function context(){return document.querySelector('input[name="observation-context"]:checked')?.value||''}
function put(id,value,empty){const el=$(id);el.textContent=value||empty;el.classList.toggle('print-empty',!value)}
function preview(){put('preview-student',f.student.value.trim(),'Student name');put('preview-week',f.week.value?`Week of ${new Date(`${f.week.value}T12:00:00Z`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})}`:'','Week of …');put('preview-skill',f.skill.selectedOptions[0]?.textContent||'','Choose a main skill');put('preview-problem',f.problem.value.trim(),'What they were trying to do');put('preview-observed',f.observed.value.trim(),'What they did');put('preview-next',f.next.value.trim(),'What to try next');const c=context();$('preview-context').textContent=c?`Seen during: ${c}`:'';$('preview-easier').textContent=f.easier.value.trim();$('preview-easier-block').hidden=!f.easier.value.trim()}
function validate(){const e=[];if(!f.student.value.trim())e.push('Choose a student.');if(!f.week.value)e.push('Choose a week.');if(!f.skill.value)e.push('Choose a main skill.');if(!f.problem.value.trim())e.push('Add what they were trying to do.');if(!f.observed.value.trim())e.push('Add what you saw.');if(!f.next.value.trim())e.push('Add what they should try next.');return e}
function reset(){f.student.value='';f.skill.value='';f.problem.value='';f.observed.value='';f.next.value='';f.easier.value='';document.querySelectorAll('input[name="observation-context"]').forEach(x=>x.checked=false);pdfPrintInvoked=false;$('new-student').disabled=true;$('form-error').hidden=true;$('save-status').textContent='';preview();f.student.focus()}
function init(){f.week.value=monday();$('new-student').disabled=true;SKILLS.forEach(([key,label])=>{const o=document.createElement('option');o.value=key;o.textContent=label;f.skill.appendChild(o)});CONTEXTS.forEach(label=>{const l=document.createElement('label');l.className='checkin-context';const i=document.createElement('input');i.type='radio';i.name='observation-context';i.value=label;const s=document.createElement('span');s.textContent=label;l.append(i,s);$('context-options').appendChild(l)});Object.values(f).forEach(x=>x.addEventListener('input',preview));$('context-options').addEventListener('change',preview);$('save-pdf').addEventListener('click',()=>{const e=validate();if(e.length){$('form-error').textContent=e.join(' ');$('form-error').hidden=false;return}const old=document.title,safe=f.student.value.trim().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'Student';document.title=`Sensei-Sandy_Check-In_${safe}_${f.week.value}`;pdfPrintInvoked=true;$('new-student').disabled=false;$('save-status').textContent='Print dialog opened. Your review stays on the page.';window.print();setTimeout(()=>{document.title=old},1000)});$('new-student').addEventListener('click',()=>{if(!pdfPrintInvoked&&(f.student.value.trim()||f.problem.value.trim()||f.observed.value.trim()||f.next.value.trim())&&!window.confirm('This review has not been opened for PDF saving. Start a new student anyway?'))return;reset()});preview()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
