(function () {
  'use strict';
  const keyInput = document.getElementById('ops-key');
  const loadButton = document.getElementById('load');
  const records = document.getElementById('records');
  const status = document.getElementById('status');
  const report = document.getElementById('report');
  const labels = { bookingInformationReviewed:'Booking information reviewed', waiverCompleted:'Waiver completed', parentAttended:'Parent attended', suitablePartnerAssigned:'Suitable partner assigned', safetyRuleExplained:'Safety rule explained', controlledGameCompleted:'Student completed one controlled game', specificSuccessIdentified:'Specific success identified', parentRecommendationReceived:'Parent received a recommendation', coreCulturePriceStated:'Core Culture price stated', nextActionRecorded:'Next action recorded', followUpScheduled:'Follow-up scheduled within 24 hours' };
  keyInput.value = sessionStorage.getItem('youthOpsKey') || '';
  function headers() { return { 'Accept':'application/json', 'Content-Type':'application/json', 'X-Ops-Api-Key':keyInput.value }; }
  async function load() { sessionStorage.setItem('youthOpsKey', keyInput.value); status.textContent = ' Loading…'; const [recordsResponse, reportResponse] = await Promise.all([fetch('/api/youth-intro/records', { headers:headers() }), fetch('/api/youth-intro/report', { headers:headers() })]); if (!recordsResponse.ok) throw new Error(`Load failed (${recordsResponse.status})`); if (!reportResponse.ok) throw new Error(`Report failed (${reportResponse.status})`); const data = await recordsResponse.json(); const reportData = await reportResponse.json(); records.replaceChildren(); data.records.forEach((record) => render(record, data.stages)); renderReport(reportData); status.textContent = ` ${data.records.length} record(s)`; }
  function renderReport(data) { const f = data.funnel; const c = data.cohort; report.replaceChildren(); const summary = document.createElement('p'); summary.textContent = `Inquiries: ${f.inquiries} · Booked: ${f.booked} · Confirmed: ${f.confirmed} · Attended: ${f.attended} · Recommended: ${f.recommended} · Enrolled: ${f.enrolled} · No-shows: ${f.noShows}`; report.appendChild(summary); const cohort = document.createElement('p'); cohort.textContent = `First-20 cohort: ${Math.min(c.attendedCount, c.target)} of ${c.target} attended${c.complete ? ' · ready for review' : ' · collection in progress'}.`; report.appendChild(cohort); if (data.nonEnrollmentReasons.length) { const list = document.createElement('ul'); data.nonEnrollmentReasons.forEach((item) => { const li = document.createElement('li'); li.textContent = `${item.reason}: ${item.total}`; list.appendChild(li); }); report.appendChild(list); } }
  function render(record, stages) { const node = document.getElementById('record-template').content.cloneNode(true); const article = node.querySelector('.record'); article.dataset.id = record.id; node.querySelector('h2').textContent = `${record.student_name || 'Student'} · age ${record.student_age || '?'}`; node.querySelector('.muted').textContent = `${record.town || ''} · preferred ${record.preferred_date || 'not set'} · ${record.student_name || ''}`; const stage = node.querySelector('[data-field="pipelineStage"]'); stages.forEach((value) => { const option = document.createElement('option'); option.value = value; option.textContent = value; stage.appendChild(option); }); stage.value = record.pipeline_stage; node.querySelectorAll('[data-field]').forEach((field) => { const key = field.dataset.field; if (key !== 'pipelineStage') field.value = record[{completionStatus:'completion_status',attendanceStatus:'attendance_status',rescheduleCount:'reschedule_count',recommendedSchedule:'recommended_schedule',followUpDate:'follow_up_date',nonEnrollmentReason:'non_enrollment_reason'}[key]] || ''; }); let savedChecklist = {}; try { savedChecklist = JSON.parse(record.checklist_json || '{}'); } catch (_) {} const list = node.querySelector('[data-checklist]'); Object.entries(labels).forEach(([key, label]) => { const wrapper = document.createElement('label'); const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.dataset.check = key; checkbox.checked = Boolean(savedChecklist[key]); wrapper.append(checkbox, ` ${label}`); list.appendChild(wrapper); }); node.querySelector('[data-save]').addEventListener('click', () => save(article)); records.appendChild(node); }
  async function save(article) { const get = (key) => article.querySelector(`[data-field="${key}"]`).value; const checklist = {}; article.querySelectorAll('[data-check]').forEach((box) => { checklist[box.dataset.check] = box.checked; }); const payload = { id:article.dataset.id, pipelineStage:get('pipelineStage'), completionStatus:get('completionStatus'), attendanceStatus:get('attendanceStatus'), rescheduleCount:get('rescheduleCount'), recommendedSchedule:get('recommendedSchedule'), followUpDate:get('followUpDate'), nonEnrollmentReason:get('nonEnrollmentReason'), checklist }; const result = article.querySelector('[data-result]'); result.textContent = ' Saving…'; const response = await fetch('/api/youth-intro/records', { method:'POST', headers:headers(), body:JSON.stringify(payload) }); const data = await response.json(); result.textContent = response.ok ? ' Saved.' : ` ${data.error || Object.values(data.errors || {}).join(' ') || 'Save failed.'}`; result.className = response.ok ? '' : 'danger'; }
  async function remove(article) { if (!window.confirm('Delete this clearly labeled test record?')) return; const result = article.querySelector('[data-result]'); const response = await fetch(`/api/youth-intro/records?id=${encodeURIComponent(article.dataset.id)}`, { method:'DELETE', headers:headers() }); if (response.ok) article.remove(); else result.textContent = ' Delete failed.'; }
  loadButton.addEventListener('click', () => load().catch((error) => { status.textContent = ` ${error.message}`; status.className = 'danger'; }));
  records.addEventListener('click', (event) => { if (event.target.matches('[data-delete]')) remove(event.target.closest('.record')); });
}());
