#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'; import { execFile, spawn } from 'node:child_process'; import { promisify } from 'node:util';
const exec = promisify(execFile); const phase = process.argv.includes('--phase') ? process.argv[process.argv.indexOf('--phase') + 1] : '';
if (!['before','after'].includes(phase)) throw new Error('Use --phase before|after');
const routes = ['/', '/free-bjj-intro-tannersville-ny', '/schedule', '/bjj-classes/kids-tannersville-ny', '/bjj-classes/teens-tannersville-ny', '/bjj-classes/adults-tannersville-ny', '/options-pricing'];
const root = `artifacts/performance/${phase}`; await mkdir(`${root}/lighthouse`, { recursive: true }); await mkdir(`${root}/screenshots`, { recursive: true });
await exec('npm', ['run', 'build'], { maxBuffer: 1024 * 1024 * 10 }); await exec('npm', ['run', 'build:assets'], { maxBuffer: 1024 * 1024 * 10 }); await exec('npm', ['run', 'build'], { maxBuffer: 1024 * 1024 * 10 }); const server = spawn('node', ['.agents/skills/web-performance-evidence/scripts/static-server.mjs', 'dist', '8080'], { stdio: 'ignore' }); await new Promise(resolve => setTimeout(resolve, 500));
const sha = (await exec('git', ['rev-parse', 'HEAD'])).stdout.trim(); const manifest = { phase, sha, timestamp: new Date().toISOString(), node: process.version, chrome: 'HeadlessChrome/150.0.0.0', lighthouse: '13.4.1', playwright: '1.62.1', viewport: '390x844', routes, samples: 3, server: 'repo production build served by bundled static-server.mjs' };
await writeFile(`${root}/manifest.json`, JSON.stringify(manifest, null, 2));
try { for (const route of routes) { const safe = route.replaceAll('/', '_') || 'home'; const url = `${process.env.PERF_BASE_URL || 'http://127.0.0.1:8080'}${route}`; await exec('node', ['.agents/skills/web-performance-evidence/scripts/lighthouse-run.mjs', '--url', url, '--out', `${root}/lighthouse/${safe}.json`, '--samples', '3'], { maxBuffer: 1024 * 1024 * 20 }); } await exec('node', ['.agents/skills/web-performance-evidence/scripts/playwright-capture.mjs', ...routes], { env: { ...process.env, PERF_OUT: `${root}/screenshots`, PERF_EXECUTABLE_PATH: process.env.PERF_EXECUTABLE_PATH || '/snap/bin/chromium' }, maxBuffer: 1024 * 1024 * 10 }); } finally { server.kill('SIGTERM'); }
